
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Oct 18 00:11:23 KST 2016
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 21;
  public static final int GE = 12;
  public static final int CASE = 35;
  public static final int LPAREN = 5;
  public static final int INT = 25;
  public static final int INTNUM = 36;
  public static final int FOR = 30;
  public static final int MINUS = 20;
  public static final int RPAREN = 6;
  public static final int SEMICOLON = 4;
  public static final int AND = 23;
  public static final int LT = 13;
  public static final int OR = 24;
  public static final int COMMA = 2;
  public static final int PLUS = 19;
  public static final int ASSIGN = 18;
  public static final int IF = 27;
  public static final int DOT = 17;
  public static final int LE = 14;
  public static final int EOF = 0;
  public static final int RETURN = 33;
  public static final int error = 1;
  public static final int FLOATNUM = 37;
  public static final int NEQ = 16;
  public static final int BREAK = 32;
  public static final int EQ = 15;
  public static final int SWITCH = 34;
  public static final int LBRACK = 9;
  public static final int TIMES = 22;
  public static final int COLON = 3;
  public static final int LBRACE = 7;
  public static final int ELSE = 28;
  public static final int RBRACK = 10;
  public static final int WHILE = 29;
  public static final int FLOAT = 26;
  public static final int RBRACE = 8;
  public static final int GT = 11;
  public static final int DO = 31;
  public static final int IDENTIFIER = 38;
}

